In [35]:

import numpy as np
import math
import numpy.linalg as la

In [36]:
class KNN:
    def __init__(self, X=np.array([]), Predict=np.array([])):
        self._Training = X
        self._Predict = Y
        
    def getTrain(self):
        return self._Training
    def getPred(self):
        return self._Predict
    
    def setTrain(self, P):
        self._Training = P
    def setPred(self, P):
        self._Predict = P
        
    def appendTrain(self):
        return self._Training
    def appendPred(self):
        return self._Predict
    
    def distances(self, points, x):#x is a 1-by-d 1 sample of d dimenssions
        return la.norm(points - x, axis=1)
    
    def kClosesestT(self, x):
        tmp = self.distances(self._Training, x) 
        tmp2 = tmp.argsort()[:3]
        rtn = np.where(tmp == tmp[0])
        rtn.append(np.where(tmp == tmp[1]))
        rtn.append(np.where(tmp == tmp[2]))
    
    

In [70]:
def distances(points, x):#x is a 1-by-d 1 sample of d dimenssions
    tmp = points - x
    print(tmp)
    return la.norm(tmp, axis=1)

k=3

arr = np.array([[1,5],[6,3],[9,15], [6, 8], [7, 9]])

tmp = distances(arr, np.array([[5, 6]])) 
print(arr)
print()
print(tmp)
t = np.sort(tmp)[:k]
print(np.where(tmp == t[0]))
print(np.where(tmp == t[1]))
print(np.where(tmp == t[2]))
rtn=[]
rtn = arr[np.where(tmp == t[0])]
print(rtn)
rtn = np.concatenate((rtn, arr[np.where(tmp == t[1])]), axis=0)
rtn = np.concatenate((rtn, arr[np.where(tmp == t[2])]), axis=0)

print(rtn)

[[-4 -1]
 [ 1 -3]
 [ 4  9]
 [ 1  2]
 [ 2  3]]
[[ 1  5]
 [ 6  3]
 [ 9 15]
 [ 6  8]
 [ 7  9]]

[ 4.12310563  3.16227766  9.8488578   2.23606798  3.60555128]
(array([3]),)
(array([1]),)
(array([4]),)
[[6 8]]
[[6 8]
 [6 3]
 [7 9]]
